INSERT INTO clientes(nombre,apellidos,empresa,puesto,provincia,cp,telefono,fecha_nacimiento) VALUES ('Patricia','Jerez Prado','Capgemini','Programador Junior','Asturias',33420,123456,'1975-07-15')
INSERT INTO clientes(nombre,apellidos,empresa,puesto,provincia,cp,telefono,fecha_nacimiento) VALUES ('Andrés','Gonzalez Fernández','Capgemini','Programador Junior','Asturias',33006,123456,'1994-05-24')
INSERT INTO clientes(nombre,apellidos,empresa,puesto,provincia,cp,telefono,fecha_nacimiento) VALUES ('David','Martínez LLano','Capgemini','Programador Junior','Asturias',33003,123456,'2001-03-9')
INSERT INTO clientes(nombre,apellidos,empresa,puesto,provincia,cp,telefono,fecha_nacimiento) VALUES ('Rafael','García I.','Capgemini','Programador Junior','Asturias',33499,123456,'1991-08-20')
INSERT INTO articulos (unidades_stock,stock_seguridad,imagen,descripcion,nombre,precio_unidad) VALUES (5,4,null,'Ratón con cable','Ratón',5.12)
INSERT INTO articulos (unidades_stock,stock_seguridad,imagen,descripcion,nombre,precio_unidad) VALUES (8,4,null,'Monitor PC gamer','Monitor Lenovo Plus++',789.99)
INSERT INTO articulos (unidades_stock,stock_seguridad,imagen,descripcion,nombre,precio_unidad) VALUES (25,31,null,'Libreta de cuadros','Lamela',7.80)
INSERT INTO articulos (unidades_stock,stock_seguridad,imagen,descripcion,nombre,precio_unidad) VALUES (63,20,null,'Adaptador HDMI - VGA','Adaptador pc',35.00)
INSERT INTO articulos (unidades_stock,stock_seguridad,imagen,descripcion,nombre,precio_unidad) VALUES (256,60,null,'Alfombrilla ergonómica','Alfombrilla ratón',7.50)
INSERT INTO articulos (unidades_stock,stock_seguridad,imagen,descripcion,nombre,precio_unidad) VALUES (50,2,null,'Sujeta cables','Chirimbolo',2.00)